# Page settings
baseurl = ""
title = "MSc Econometrics"
languageCode = "en-us"
theme = "hugo-elate-theme"
publishDir = "docs"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""

  # Google Maps Javascript API Key (if not set will default to not passing a key)
  googleMapsApiKey = ""

  # Navigation
  [params.navigation]
    brand = ''
    home = "Home"
    work = "The Program"
    testimonials = "Testimonials"
    services = "Application"
    about = "Coordinators"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "<it>Econometrics<it>"
    subtitle = 'A Joint MSc Program of the Universities <br><br> TU Dortmund University <br> Ruhr University Bochum <br> University of Duisburg-Essen'
    
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Courses"
    description = "Get an overview over the program structure and more detailed information about the curriculum."
    url = "blog/overview/"
    button = "Course Overview"
    icon = "icon-compass"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Documents"
    description = "Further information on current conditions of study and admission requirements."
    url = "https://www.statistik.tu-dortmund.de/index.php?id=2705"
    button = "Faculty Page"
    icon = "icon-notebook"
    img = "img_10.jpg"


  # Work section
  [params.work]
    enable = true
    title = "About the Program"
    description = "<span>*Econometrics* is a four-semester, English-language master's program of TU Dortmund (TUDO), Ruhr-University Bochum (RUB) and the University of Duisburg-Essen (UDE). The program is carried out jointly by the faculties of economics of the three universities and the Faculty of Statistics @ TU Dortmund. It combines the expertise and breadth of the participating faculties in empirical economic research and economics with the methodically oriented training of the statisticians and econometricians at Germany's unique Faculty of Statistics. This bundling of training and research skills enables a specialized curriculum for quantitatively-oriented students which covers a wide range of topics in econometrics and applied economics.<br>Students acquire the ability to combine their statistical methodological competence with their proficiency in economics and apply both in an interdisciplinary manner. They gain extensive knowledge of econometric methods and models and an in-depth understanding of central economic causal relationships and resulting econometric questions. The program particularly supports research-interested students in developing theoretical-analytical skills with regard to specific research questions in economics and thus prepares optimally for a doctorate in econometrics or neighbouring disciplines. The master's program in Econmetrics thus prepares well for a career in econometrics, empirical economics research, evidence-based policy counselling, or operational research. Graduates receive a joint MSc degree from the four participating faculties.</span>"
    uartitle = "*University Alliance Ruhr*"
    uartext = "The University Alliance Ruhr (UAR) is a joint venture of TUDO, RUB and UDE. With more than 120.000 students and almost 1.300 professors, the UAR is one of Germany's largest and most efficient science locations. It bundles interests of the members by initiating cooperations in research, teaching and administration. Both the education of economists and the economic research of the three participating universities benefit from these joint activities, in particular through the RWI - Leibniz Institute for Economic Research and the RGS - Ruhr Graduate School in Economics which offers a fast-track PhD program in economics. Excellent graduates of *Econometrics* thus have good prospects for pursuing a further career in academics or economic research."
    footertext = ''

#    [[params.work.row]]
#      img = "UARuhrimage.jpg"
#      alt = "Image2"
#      title = ""
#      subtitle = ""
      
#    [[params.work.row]]
#      img = "caffelatte.jpg"
#      alt = "Image2"
#      title = ""
#      subtitle = ""

# Services section
  [params.services]
    link = "https://www.statistik.tu-dortmund.de/index.php?id=2705"
    enable = true
    title = "Requirements & Application"
    description = "Interested in taking up the Master's program in *Econometrics*? Please make sure that you are eligible for application and check that you meet the below criteria. Intake is every fall. Application beginns in June. Deadline is **July 15, 2019**. We are looking forward towards your application!"
    
    [[params.services.item]]
      title = "Qualifying Degrees"
    description = "The program is aimed at graduates which hold a BSc or equivalent degree in Economics, Mathematics, Statistics or a related discipline. At least 15 ECTS in each Economics, Mathematics or Statistics are required."
      icon = "icon-graduation"

    [[params.services.item]]
      title = "Academic Curriculum Vitae"
      description = "Applicants must enclose a CV which focuses on their academic background. The CV must be submitted in electronic format and should not exceed a length of two pages."
      icon = "icon-layers2"
      
    [[params.services.item]]
      title = "English Language Proficiency"
      description = "*Econometrics* is an English-language Master's program. Candidates must provide evidence of sufficient knowledge of English. We accept certificates for the following English-language tests: TOEFL paper- and pencil test, TOEFL internet-based test, International English Language Testing System (IELTS) - Academics."
      icon = "icon-badge"

  # About section
  [params.about]
    enable = true
    title = "Coordinators"

    [[params.about.item]]
      name = "Carsten Jentsch"
      position = "TU Dortmund University"
      description = "Carsten Jentsch studied mathematics with a minor in business administration at TU Braunschweig from 2001 to 2007, where he received his doctorate in 2010. After a research stay at UC San Diego he became postdoc at the Economics faculty of the University of Mannheim in 2011 and at the SFB 884 'The Political Economy of Reforms'. Since 2015 he has been a member of the Elite Program for Postdocs of the Baden-W체rttemberg Foundation. After holding professorships at the Universities of Bayreuth and Mannheim, he has been working at TU Dortmund University since summer 2018. He is a member of the RGS Faculty at the Ruhr Graduate School in Economics."
      img = "Jentsch.png"
      alt = "Person1"

    [[params.about.item]]
      name = "Christoph Hanck"
      position = "University of Duisburg-Essen"
      description = "Christoph Hanck is Professor of Econometrics at University of Duisburg-Essen since August 2012. He received his doctorate in 2007, supervised by Prof. Dr. Walter Kr채mer, from TU Dortmund University. He subsequently joined the DFG Sonderforschungsbereich 'Complexity Reduction in Multivariate Data Structures' to then become a Postdoctoral Researcher at Maastricht University in 2008. From 2009 to 2012 he was Assistant and later Associate Professor in Statistics and Econometrics at Rijksuniversiteit Groningen. His research in confined with the analysis of nonstationary panel data and macroeconometrics. He is a member of the RGS Faculty at the Ruhr Graduate School in Economics."
      img = "hanck.png"
      alt = "Person2"

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Contact"
    description = "If you have any questions regarding the program, please feel free to contact the <a href='https://www.statistik.tu-dortmund.de/fachschaftsrat_eng.html'>student council</a> at TU Dortmund University or our coordinators (via the contact form below)."
    
    # Available icons: https://coreui.io/v1/demo/pro/AngularJS_Demo/#!/icons/simple-line-icons
    details = [
        ["icon-home", "Fakult채t Statistik <br> Technische Universit채t Dortmund <br> Vogelpothsweg 87 <br> 44227 Dortmund"],
        ["icon-globe", '<a href="https://www.statistik.tu-dortmund.de" target="_blank">Faculty website</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '<br><div><img src="images/mercur.png" height="100" hspace="20"><img src="images/statistik_dortmund.png" height="55" hspace = "20"><img src="images/wiwi_dortmund.png" height="60" hspace = "21"><img src="images/wiwi_bochum.png" height="60" hspace = "20"><img src="images/wiwi_essen.png" height="60" hspace = "20"><img src="images/RGS.JPG" height="60"><br><br>The participating universities do not take any liability for the correctness and completeness of the information on their websites. The same applies to the contents of linked pages.</div>'
